name: php-cs-fixer

on:
    pull_request:
        branches:
            - main
        types: [closed]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: master

            - name: Run PHP CS Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                  args: --config=.php_cs.dist --allow-risky=yes

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: main
                  commit_message: >
                      chore: styling
